# Opacity for highlighting windows that are being used
inactive-opacity = 0.80;
active-opacity = 1.0;
frame-opacity = 0.80;

# # Fading in between windows
# fading = true;
# fade-in-step = 0.05
# fade-out-step = 0.05
