################ Fonts ###################
font_family monospace
bold_font auto
italic_font auto
bold_italic_font auto

font_size 16.0

scrollback_lines 1000


################ Bell ###################
enable_audio_bell no

################ Padding ###################
window_padding_width 10


################ Tabs ###################
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2

################ Shell/Editor ###################
shell zsh
editor nvim

# no need for kitty to check for updates
update_check_interval 0

################ Additional configs ###################
include ./OneDark.conf
