# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
align=center
separator=false
color=#f8f8f2
separator_block_width=15
markup=pango


[mediaplayer]
command=playerctl metadata --format "{{ artist }} <span color=\"#bd93f9\">-</span> {{ title }}"
interval=2
label=<span color="#bd93f9"> </span>
border=#bd93f9
border_top=1
border_right=0
border_bottom=0
border_left=0

[wifi]
command=iwgetid -r | tr '\n' ' ' && grep $(iwgetid -m | awk '{ printf "%s", $1 }') /proc/net/wireless | awk '{ printf "%i%\n", int($3 * 100 / 70) }'
instance=wlp11s0f3u1
label=<span color="#ff79c6"> </span> 
interval=5
border=#ff79c6
border_top=1
border_right=0
border_bottom=0
border_left=0

[battery]
command=/usr/local/bin/battery.sh
interval=2
label=<span color="#ff5555"> </span>
color=#ff5555
border=#ff5555
border_top=1
border_right=0
border_bottom=0
border_left=0

[arch_update]
command=checkupdates | wc -l
interval=once
label=<span color="#1793d1"> </span>
border=#1793d1
border_top=1
border_right=0
border_bottom=0
border_left=0

[volume]
command=pulseaudio-ctl full-status | awk '{ printf "%i<span color=\"#bd93f9\">%</span>\n", $1 }'
interval=1
label=<span color="#bd93f9"> </span>
border=#bd93f9
border_top=1
border_right=0
border_bottom=0
border_left=0

[memory]
command=free --giga | awk 'FNR==2{ printf "%i<span color=\"#ff79c6\">GiB</span>\n", $7 }'
interval=5
label=<span color="#ff79c6"> </span>
border=#ff79c6
border_top=1
border_right=0
border_bottom=0
border_left=0

[root]
command=df -h / | awk 'FNR==2 { gsub(/[A-Za-z]/, ""); printf "%i<span color=\"#f1fa8c\">GiB</span>\n", $4 }'
interval=3
label=<span color="#f1fa8c"> </span>
border=#f1fa8c
border_top=1
border_right=0
border_bottom=0
border_left=0

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
